id: IF0EB73FF
ocr_import_info:
  timestamp: '2023-06-28T07:55:22.553984+00:00'
  batch_id: batch-d3b8
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 08:17:38.911445+00:00
last_modified: 2023-06-28 08:17:38.911451+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22571
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22571
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བ་མདོ་རྩ་བ། ༼པར་པ་དཔལ་ལྡན་པར་མ།༽
  languages:
  - bo
  author: སློབ་དཔོན་ཡོན་ཏན་འོད།
statistics:
  ocr_word_mean_confidence_index: 0.9662984818147076
  ocr_word_median_confidence_index: 0.9994883
bases:
  I1KG22583:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22583
      total_pages: 562
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22583.txt
    statistics:
      ocr_word_median_confidence_index: 0.9994883
      ocr_word_mean_confidence_index: 0.9662984818147076
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
